# Generated by Django 3.1.5 on 2021-01-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcooking', '0003_favorit_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='nama',
        ),
    ]
