# Generated by Django 3.1.5 on 2021-01-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcooking', '0004_remove_userprofileinfo_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorit',
            name='no_fav',
            field=models.IntegerField(null=True),
        ),
    ]
