# Generated by Django 3.1.5 on 2021-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcooking', '0006_auto_20210125_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorit',
            name='foto',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='foto',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='rekomend',
            name='foto',
            field=models.FileField(upload_to='img/'),
        ),
    ]
